spring:
  profiles:
    active: dev
---
spring:
  profiles: dev 
  application:
    name: aaaaaaaa
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://root:123456@www.7a118.cn:8083/eureka/
server:
  port: 8091  
