spring:
  profiles:
    active: dev
---
spring:
  profiles: dev 
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://root:123456@localhost:8081/eureka/
app:
  name: 12221212121
